### ISSUE TITLE
Support React 0.14.x

### ISSUE THREAD

**Issue by kwtangerine** [vn38minhtran/react-revalidator#1]
The package specifies react `v0.13.x` as peerDepencency. Can we please add support for react `v0.14.x` as well?

**Comment by kwtangerine** [comment]
I have a local branch that addresses this issue. I'd like to submit a PR  but I don't have access.

**Comment by vn38minhtran** [comment]
Sorry! this is deprecated plugin and no more maintenance. You can use https://github.com/vn38minhtran/react-validation-decorator or https://github.com/jurassix/react-validation-mixin instead

**Comment by kwtangerine** [comment]
Too bad..  :(
Thanks for the reply though; will check those packages instead!
